// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	config "github.com/edgexfoundry/go-mod-bootstrap/v2/config"

	mock "github.com/stretchr/testify/mock"
)

// Configuration is an autogenerated mock type for the Configuration type
type Configuration struct {
	mock.Mock
}

// EmptyWritablePtr provides a mock function with given fields:
func (_m *Configuration) EmptyWritablePtr() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// GetBootstrap provides a mock function with given fields:
func (_m *Configuration) GetBootstrap() config.BootstrapConfiguration {
	ret := _m.Called()

	var r0 config.BootstrapConfiguration
	if rf, ok := ret.Get(0).(func() config.BootstrapConfiguration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.BootstrapConfiguration)
	}

	return r0
}

// GetInsecureSecrets provides a mock function with given fields:
func (_m *Configuration) GetInsecureSecrets() config.InsecureSecrets {
	ret := _m.Called()

	var r0 config.InsecureSecrets
	if rf, ok := ret.Get(0).(func() config.InsecureSecrets); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.InsecureSecrets)
		}
	}

	return r0
}

// GetLogLevel provides a mock function with given fields:
func (_m *Configuration) GetLogLevel() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetRegistryInfo provides a mock function with given fields:
func (_m *Configuration) GetRegistryInfo() config.RegistryInfo {
	ret := _m.Called()

	var r0 config.RegistryInfo
	if rf, ok := ret.Get(0).(func() config.RegistryInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.RegistryInfo)
	}

	return r0
}

// GetTelemetryInfo provides a mock function with given fields:
func (_m *Configuration) GetTelemetryInfo() *config.TelemetryInfo {
	ret := _m.Called()

	var r0 *config.TelemetryInfo
	if rf, ok := ret.Get(0).(func() *config.TelemetryInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.TelemetryInfo)
		}
	}

	return r0
}

// UpdateFromRaw provides a mock function with given fields: rawConfig
func (_m *Configuration) UpdateFromRaw(rawConfig interface{}) bool {
	ret := _m.Called(rawConfig)

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}) bool); ok {
		r0 = rf(rawConfig)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// UpdateWritableFromRaw provides a mock function with given fields: rawWritableConfig
func (_m *Configuration) UpdateWritableFromRaw(rawWritableConfig interface{}) bool {
	ret := _m.Called(rawWritableConfig)

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}) bool); ok {
		r0 = rf(rawWritableConfig)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
